-- 코드를 입력하세요
SELECT USED_GOODS_USER.USER_ID, NICKNAME, SUM(PRICE)
FROM USED_GOODS_USER
JOIN USED_GOODS_BOARD
ON USED_GOODS_USER.USER_ID = USED_GOODS_BOARD.WRITER_ID
WHERE STATUS = 'DONE'
GROUP BY USED_GOODS_BOARD.WRITER_ID
HAVING SUM(PRICE) >= 700000
ORDER BY SUM(PRICE)