-- 코드를 입력하세요
SELECT CATEGORY, SUM(SALES) AS TOTAL_SALES
FROM BOOK
JOIN BOOK_SALES
ON BOOK.BOOK_ID = BOOK_SALES.BOOK_ID
WHERE DATE_FORMAT(BOOK_SALES.SALES_DATE, '%Y%m') = '202201'
GROUP BY CATEGORY
HAVING SUM(SALES)
ORDER BY CATEGORY