-- 코드를 입력하세요
SELECT CAR_ID, MAX(IF(DATE_FORMAT(START_DATE, '%Y%m%d') <= '20221016' AND DATE_FORMAT(END_DATE, '%Y%m%d') >= '20221016', '대여중','대여 가능')) AS AVAILABILITY
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
GROUP BY CAR_ID
ORDER BY CAR_ID DESC